import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryBlokProvider from '@/Components/StoryBlokProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

 
storyblokInit({
  accessToken: "jrs3tuQzp4LHIlRTEI4uDwtt",
  use: [apiPlugin],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoryBlokProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </StoryBlokProvider>
  )
}
